name       : xorg-driver-input-evdev
version    : 2.10.5
release    : 16
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-evdev-2.10.5.tar.gz : df5d644cbf2eb8c4c3d232c90cfe322959e50c9b608457c1cf3c0385bc6d60f6
license    :
    - MIT
summary    : Generic Linux input driver
component  : xorg.driver
optimize   : no-bind-now
builddeps  :
    - pkgconfig(mtdev)
    - pkgconfig(xorg-server)
    - pkgconfig(libevdev)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
description: |
    The Xorg Evdev Driver package contains Generic Linux input driver for the Xorg X server. It handles keyboard, mouse, touchpads and wacom devices, though for touchpad and wacom advanced handling, additional drivers are required. .
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
