name        : xorg-driver-input-evdev
version     : 2.10.1
release     : 12
source      :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-input-evdev-2.10.1.tar.gz : 1b93249934a1f79bfa87d99ba730762bec504664347f7a00cf0fa7a0f353bf73
license     :
    - MIT
summary     : Generic Linux input driver
component   : xorg.driver
optimize    : no-bind-now
builddeps   :
    - pkgconfig(mtdev)
    - pkgconfig(xorg-server)
    - pkgconfig(libevdev)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
description : |
    The Xorg Evdev Driver package contains Generic Linux input driver for the Xorg X server. It handles keyboard, mouse, touchpads and wacom devices, though for touchpad and wacom advanced handling, additional drivers are required. .
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
