name       : xorg-driver-input-evdev
version    : 2.10.3
release    : 13
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-evdev-2.10.3.tar.gz : d188e3046b385d54a78312978cdb6c48992d5c252d805bcf74e1ef23efa5aabc
license    :
    - MIT
summary    : Generic Linux input driver
component  : xorg.driver
optimize   : no-bind-now
builddeps  :
    - pkgconfig(mtdev)
    - pkgconfig(xorg-server)
    - pkgconfig(libevdev)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
description: |
    The Xorg Evdev Driver package contains Generic Linux input driver for the Xorg X server. It handles keyboard, mouse, touchpads and wacom devices, though for touchpad and wacom advanced handling, additional drivers are required. .
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
