name       : xorg-driver-input-evdev
version    : 2.10.4
release    : 14
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-evdev-2.10.4.tar.gz : 1a1b69daf41eac965f1cf0be721ebc340b2860c066147cb483f0e8f0ab7dd6a2
license    :
    - MIT
summary    : Generic Linux input driver
component  : xorg.driver
optimize   : no-bind-now
builddeps  :
    - pkgconfig(mtdev)
    - pkgconfig(xorg-server)
    - pkgconfig(libevdev)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
description: |
    The Xorg Evdev Driver package contains Generic Linux input driver for the Xorg X server. It handles keyboard, mouse, touchpads and wacom devices, though for touchpad and wacom advanced handling, additional drivers are required. .
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
